export const CLEAR_TOAST = 'CLEAR_TOAST';
export const SET_PENDING_UPDATES_COUNT = 'SET_PENDING_UPDATES_COUNT';
export const SET_PENDING_UPDATES = 'SET_PENDING_UPDATES';
export const PUBLISH_SUCCESS = 'PUBLISH_SUCCESS';
export const PUBLISH_ERROR = 'PUBLISH_ERROR';
export const CLEAR_UPDATES_ERROR = 'CLEAR_UPDATES_ERROR';

export const DELETE_TASK_SUCCESS = 'DELETE_TASK_SUCCESS';

export const UPDATE_TASK_ERROR = 'UPDATE_TASK_ERROR';
export const UPDATE_TASK_SUCCESS = 'UPDATE_TASK_SUCCESS';
