export const CLEAR_ADMIN_TOAST = 'CLEAR_ADMIN_TOAST';
export const SET_PENDING_UPDATES_COUNT = 'SET_PENDING_UPDATES_COUNT';
export const SET_PENDING_UPDATES = 'SET_PENDING_UPDATES';
export const PUBLISH_SUCCESS = 'PUBLISH_SUCCESS';
export const PUBLISH_ERROR = 'PUBLISH_ERROR';
export const CLEAR_UPDATES_SUCCESS = 'CLEAR_UPDATES_SUCCESS';
export const CLEAR_UPDATES_ERROR = 'CLEAR_UPDATES_ERROR';
