export const CLEAR_ADMIN_TOAST = 'CLEAR_ADMIN_TOAST';
export const DELETE_GALLERIES_CATEGORY = 'DELETE_GALLERIES_CATEGORY';
export const SET_PENDING_UPDATES_COUNT = 'SET_PENDING_UPDATES_COUNT';
export const SET_PENDING_UPDATES = 'SET_PENDING_UPDATES';
export const CLEAR_PENDING_UPDATES = 'CLEAR_PENDING_UPDATES';
export const CLEAR_UPDATES_ERROR = 'CLEAR_UPDATES_ERROR';
