export const CUSTOMER_SIGN_IN_SUCCESS = 'CUSTOMER_SIGN_IN_SUCCESS';
export const HYDRATE_AUTH = 'HYDRATE_AUTH';
export const HYDRATE_CUSTOMER_AUTH = 'HYDRATE_CUSTOMER_AUTH';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_ERROR = 'SIGN_IN_ERROR';
export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';
export const RESET_AUTH_MESSAGES = 'RESET_AUTH_MESSAGES';
