export const CLEAR_TOAST = 'CLEAR_TOAST';
export const INIT_GALLERIES = 'INIT_GALLERIES';
export const TOGGLE_GALLERY_EDIT = 'TOGGLE_GALLERY_EDIT';
export const HIGHLIGHT_GALLERIES_LINK = 'HIGHLIGHT_GALLERIES_LINK';
export const UPLOAD_GALLERY_IMAGE_SUCCESS = 'UPLOAD_GALLERY_IMAGE_SUCCESS';
export const UPLOAD_GALLERY_IMAGE_ERROR = 'UPLOAD_GALLERY_IMAGE_ERROR';
