export const INIT_HOME_GALLERY_ONE = 'INIT_HOME_GALLERY_ONE';
export const INIT_HOME_GALLERY_TWO = 'INIT_HOME_GALLERY_TWO';
export const INIT_GALLERIES = 'INIT_GALLERIES';
export const TOGGLE_GALLERY_EDIT = 'TOGGLE_GALLERY_EDIT';
export const SUBMIT_GALLERY_IMAGE_URL_SUCCESS = 'SUBMIT_GALLERY_IMAGE_URL_SUCCESS';
export const SUBMIT_GALLERY_IMAGE_URL_ERROR = 'SUBMIT_GALLERY_IMAGE_URL_ERROR';
export const CREATE_TASK_SUCCESS = 'CREATE_TASK_SUCCESS';

export const DELETE_TASK_ERROR = 'DELETE_TASK_ERROR';
export const DELETE_TASK_SUCCESS = 'DELETE_TASK_SUCCESS';

export const UPDATE_TASK_ERROR = 'UPDATE_TASK_ERROR';
export const UPDATE_TASK_SUCCESS = 'UPDATE_TASK_SUCCESS';
